[package]
name = "haw-mensa"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
mensa-crawler = { version = "4.0.0", path = "./mensa-crawler" }
